### ISSUE TITLE
Can't resolve 'blurhash' in 'react-blurhash/es'

### ISSUE THREAD

**Issue by pnfcre** [woltapp/react-blurhash#5]
Hi there,

I tried using this package in my Next.js app, but I'm getting the following error including the module with `import { Blurhash } from 'react-blurhash'`:

```
[ error ] ./node_modules/react-blurhash/es/BlurhashCanvas.js
Module not found: Can't resolve 'blurhash' in 'C:\Development\node_modules\react-blurhash\es'
```

Kind regards,
Hampus Kraft.

**Comment by pnfcre** [comment]
Oh, wait. I'm stupid. Nevermind!

**Comment by blackr1234** [comment]
For those who come to this post, the reason for getting this error is that you will need to npm-install the package `blurhash` as well.

As mentioned in the **Install** section:

> npm install --save blurhash react-blurhash
