### ISSUE TITLE
Alternative for React-Native

### ISSUE THREAD

**Issue by mrousavy** [woltapp/react-blurhash#8]
Have you found an alternative approach for this, by instead of using a `canvas` to use something that works on React Native?

I haven't found a single Image library or documentation on how to create a raw pixel array (`UInt8ClampedArray`) into an Image (or anything that's somewhat helpful, like a base64 representation)

**Comment by mrousavy** [comment]
I have created a lightweight and fast native module for React Native which can **decode** and **encode** blurhashes straight out of react native. It can decode asynchronously and is pretty performance optimized, as it decodes and renders everything natively for iOS and Android. Check it out at [mrousavy/react-native-blurhash](https://github.com/mrousavy/react-native-blurhash)!

**Comment by Thisen** [comment]
Nice alternative! Lets close this then.
